volumes:
  nginx_conf:
    name: nginx_conf
  static_volume:
    name: static_volume
  postgres_data:
    name: postgres_data

networks:
  app:
    name: app
  web_net:
    external: true

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: myapp-nginx
    hostname: myapp-nginx
    # no "ports:", Traefik is the only public entrypoint
    expose:
      - 80
    depends_on:
      - api
    volumes:
      - nginx_conf:/etc/nginx/conf.d/
      - static_volume:/usr/src/app/static
    networks:
      - app
      - web_net
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web_net"

      # HTTP -> HTTPS redirect
      - "traefik.http.middlewares.myapp-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.myapp.entrypoints=http"
      - "traefik.http.routers.myapp.rule=Host(`${APP_NAME}.${TRA_DOMAIN}`)"
      - "traefik.http.routers.myapp.middlewares=myapp-redirect"

      # HTTPS router
      - "traefik.http.routers.myapp-secure.entrypoints=https"
      - "traefik.http.routers.myapp-secure.rule=Host(`${APP_NAME}.${TRA_DOMAIN}`)"
      - "traefik.http.routers.myapp-secure.tls=true"
      - "traefik.http.routers.myapp-secure.tls.certresolver=mycert"
      - "traefik.http.services.myapp.loadbalancer.server.port=80"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    hostname: api
    expose:
      - 8000
    networks:
      - app
    env_file:
      - .env
    volumes:
      - static_volume:/usr/src/app/static
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    restart: always
    depends_on:
      - postgres
      - redis

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celery
    hostname: celery
    networks:
      - app
    env_file:
      - .env
    command: celery -A core worker -l INFO
    restart: always
    depends_on:
      - postgres
      - redis

  redis:
    image: redis:7.0-alpine
    container_name: redis
    hostname: redis
    restart: always
    networks:
      - app

  postgres:
    image: postgres:16-alpine
    container_name: postgres
    hostname: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app
    environment:
      TZ: Europe/Berlin
    env_file:
      - db.env
